server:
  port: 8081

cloud:
  aws:
    s3:
      bucket: shimpyo-image-bucket
    credentials:
      accessKey: temp
      secretKey: temp
    stack.auto: false
    region.static: ap-northeast-2

spring:
#  profiles:
#    include: db, oauth
  config:
    import: db-config.yml, application-oauth.yml

  #    config import 지정해줘야 데이터 저장됨
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 20GB
  jwt:
    secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  #    defer-datasource-initialization: true
  #        use_sql_comments: true

  data:
    web:
      pageable:
        default-page-size: 100

  logging.level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: temp
            redirect-uri: https://shimpyo-api.p-e.kr:8081/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email #동의 항목
            client-name: Kakao

          google:
            client-id: temp
            client-secret: temp
            #            token-uri: https://oauth2.googleapis.com/token
            redirect-uri: https://shimpyo-api.p-e.kr:8081/login/oauth2/code/google # 이 uri에 코드 값을 넘겨준다
            #            resource-uri: https://www.googleapis.com/oauth2/v2/userinfo
            scope:
              - email
              - profile

          naver:
            client-id: temp
            client-secret: temp
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: https://shimpyo-api.p-e.kr:8081/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id



